from utils.registry import DETECTOR
from .fair_df_detector import FairDetector
from .xception_detector import XceptionDetector
from .daw_fdd import DawFddDetector
from .efficientnetb4_detector import EfficientDetector
from .f3net_detector import F3netDetector
from .spsl_detector import SpslDetector
from .ucf_detector import UCFDetector
from .srm_detector import SRMDetector
from .dag_fdd import DagFddDetector
from .core_detector import CoreDetector
